<?php
// ─── Server-Side Concepts Demo ────────────────────────────────────────────
// Everything here runs on the SERVER before the page is sent to the browser.

$serverOS      = PHP_OS;
$phpVersion    = PHP_VERSION;
$serverTime    = date('Y-m-d H:i:s');
$clientIP      = $_SERVER['REMOTE_ADDR'];
$requestMethod = $_SERVER['REQUEST_METHOD'];
$userAgent     = htmlspecialchars($_SERVER['HTTP_USER_AGENT']);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Server-Side Info</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 650px; margin: 60px auto; background: #f4f4f4; }
        .card { background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
        h1 { color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #eee; }
        th { background: #007bff; color: #fff; }
        tr:hover { background: #f9f9f9; }
        code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-size: 13px; }
        .note { margin-top: 20px; background: #fff8e1; padding: 15px; border-radius: 6px; font-size: 14px; }
        a { display: inline-block; margin-top: 20px; color: #007bff; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
<div class="card">
    <h1>Server-Side Information</h1>
    <p>This data was generated by PHP <strong>on the server</strong> — not by JavaScript in your browser.</p>

    <table>
        <tr><th>Property</th><th>Value</th></tr>
        <tr><td>PHP Version</td><td><?= $phpVersion ?></td></tr>
        <tr><td>Server OS</td><td><?= $serverOS ?></td></tr>
        <tr><td>Server Date &amp; Time</td><td><?= $serverTime ?></td></tr>
        <tr><td>Your IP Address</td><td><?= $clientIP ?></td></tr>
        <tr><td>Request Method</td><td><?= $requestMethod ?></td></tr>
        <tr><td>Your Browser</td><td><?= $userAgent ?></td></tr>
    </table>

    <div class="note">
        <strong>Key Concepts:</strong>
        <ul>
            <li><strong>Frontend:</strong> HTML, CSS, JavaScript — runs in the <em>browser</em>.</li>
            <li><strong>Backend:</strong> PHP — runs on the <em>server</em>. The user only sees the output (HTML), never the PHP code.</li>
            <li><strong>Request:</strong> Browser asks the server for a page (GET) or sends data (POST).</li>
            <li><strong>Response:</strong> Server processes the request and sends back HTML.</li>
            <li><code>$_POST</code> — holds form data sent via POST method.</li>
            <li><code>$_GET</code> — holds data sent via URL query string.</li>
            <li><code>$_SERVER</code> — holds server &amp; request environment info.</li>
        </ul>
    </div>

    <a href="index.html">← Back to Form</a>
</div>
</body>
</html>
