<?php
// ─── Server-Side Processing ───────────────────────────────────────────────
// $_POST holds data sent from the HTML form via HTTP POST request.
// This runs on the SERVER – the user never sees this PHP code.

// Validate: redirect back if accessed directly without form data
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: index.html');
    exit;
}

// Sanitize inputs to prevent XSS
$name   = htmlspecialchars(trim($_POST['username']));
$email  = htmlspecialchars(trim($_POST['email']));
$course = htmlspecialchars(trim($_POST['course']));

// Server-side validation
$errors = [];
if (empty($name))   $errors[] = "Name is required.";
if (empty($email))  $errors[] = "Email is required.";
if (empty($course)) $errors[] = "Course is required.";

// Get current time dynamically on the server
$time     = date('H:i:s');
$date     = date('l, d F Y');
$greeting = (date('H') < 12) ? "Good morning" : ((date('H') < 18) ? "Good afternoon" : "Good evening");
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome – <?= $name ?></title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 60px auto; background: #f4f4f4; }
        .card { background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
        .welcome { font-size: 26px; color: #007bff; font-weight: bold; }
        .detail { margin: 8px 0; color: #555; }
        .detail span { font-weight: bold; color: #333; }
        .error { background: #fdecea; color: #c0392b; padding: 12px; border-radius: 6px; }
        .server-info { margin-top: 25px; background: #eafaf1; padding: 15px; border-radius: 6px; font-size: 14px; }
        .server-info h3 { margin-top: 0; color: #1a7a4a; }
        a { display: inline-block; margin-top: 20px; color: #007bff; text-decoration: none; }
        a:hover { text-decoration: underline; }
        code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-size: 13px; }
    </style>
</head>
<body>
<div class="card">

<?php if (!empty($errors)): ?>
    <div class="error">
        <strong>Please fix the following:</strong>
        <ul><?php foreach ($errors as $e) echo "<li>$e</li>"; ?></ul>
    </div>
    <a href="index.html">← Go back</a>

<?php else: ?>
    <!-- Dynamic content generated by PHP on the server -->
    <p class="welcome"><?= $greeting ?>, <?= $name ?>! 👋</p>

    <p class="detail">📧 Email: <span><?= $email ?></span></p>
    <p class="detail">🎓 Course: <span><?= $course ?></span></p>
    <p class="detail">🕐 Server Time: <span><?= $time ?></span></p>
    <p class="detail">📅 Date: <span><?= $date ?></span></p>

    <div class="server-info">
        <h3>What Just Happened (Backend)</h3>
        <ul>
            <li>Your browser sent a <code>POST</code> request to <code>welcome.php</code>.</li>
            <li>PHP read your data from <code>$_POST['username']</code>, <code>$_POST['email']</code>, etc.</li>
            <li>PHP sanitized inputs using <code>htmlspecialchars()</code> to prevent XSS.</li>
            <li>PHP generated the current date/time using <code>date()</code> — this runs on the server, not your browser.</li>
            <li>The server sent back this HTML page as the <strong>HTTP Response</strong>.</li>
        </ul>
        <p><strong>Frontend vs Backend:</strong><br>
        The HTML form is <em>frontend</em> (runs in your browser). This PHP logic is <em>backend</em> (runs on the server — you never see the PHP source code).</p>
    </div>

    <a href="index.html">← Submit another response</a>
<?php endif; ?>

</div>
</body>
</html>
